name: health_monitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.1
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
